CC=gcc -g

#Executable Name
program_Name := Integrate

all: Integrate
#Default Taget
all: $(programs_Name)
#Defualt Dependenciess
$(program_Name): Integrate.c 
	$(CC) -o $(program_Name) Integrate.c
clean:
	rm Integrate	
